# -*- coding: utf-8 -*-
"""Colon_tests/01_test_preprocessing.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lGzG0d5wj-buMq4Qlj7PLPykmXenV4Mi

# 01_test_preprocessing.py
# Test script for preprocessing colorectal cancer dataset
"""

# 1. Connect to Google Drive for File Access
from google.colab import drive
drive.mount('/content/drive')

"""**Step #1** is about establishing access to your files by mounting Google Drive inside the Colab environment. The code imports the google.colab.drive module and mounts your Drive at /content/drive, which lets the notebook read and write files as if they were local. When Colab reports that the drive is “already mounted,” it simply means the connection is active and ready for use.

**(Why This Step Matters)**
This step matters because it anchors your entire workflow to a stable, long‑term storage location. For clinical research pipelines—where datasets are large, sensitive, and version‑controlled—having a reliable storage mount ensures that every subsequent step (data loading, cleaning, modeling, exporting results) operates on consistent, traceable files. It also supports reproducibility, collaboration, and seamless continuation of work across sessions.
"""

# 2. Load Core Data Analysis Libraries
import pandas as pd
import numpy as np

"""**Step #2** introduces the core analytical tools your workflow depends on by importing pandas and numpy, two foundational Python libraries for data manipulation and numerical computation. This step prepares the environment so you can load datasets, clean variables, transform columns, compute statistics, and build reproducible data structures throughout the pipeline.

**(Why This Step Matters)**
This step matters because every subsequent operation in your pipeline relies on these libraries being available and consistently referenced. Without importing them at the start, your notebook would fail as soon as you attempt to load data, calculate statistics, or manipulate arrays. For clinical datasets—often large, multi-table, and sensitive—using standardized, well‑tested libraries ensures accuracy, reproducibility, and computational efficiency. It also sets a clear, professional foundation for collaborators who expect these imports at the top of any analysis script.
"""

import os

# 3. Verify and Load Dataset
data_path = "/content/drive/MyDrive/colorectal_cancer_prediction_cleaned_imputed.csv"

if not os.path.exists(data_path):
    print(f"Warning: File not found by os.path.exists at {data_path}. This might lead to an error below.")
else:
    print(f"Info: File found by os.path.exists at {data_path}. Attempting to load with pandas...")

df = pd.read_csv(data_path)

"""**Step 3** focuses on verifying that your dataset exists at the expected location in Google Drive and then loading it into a pandas DataFrame. The code checks the file path using os.path.exists, prints a clear status message about whether the file was found, and then uses pd.read_csv to import the dataset into memory. This creates the foundational object—df—that the rest of your workflow will operate on.

**(Why This Step Matters)**
This step matters because every downstream operation—cleaning, exploration, modeling, evaluation—depends on successfully loading the correct dataset. A missing or mis-specified file path can derail an entire pipeline, especially in clinical research where datasets are large, sensitive, and version-controlled. By explicitly checking for the file and reporting its status, you create a transparent, reproducible workflow that helps collaborators diagnose issues quickly and ensures that the analysis always begins with the intended data source.
"""

# 4. Review Dataset Dimensions and Variables
print("\n=== Dataset Shape ===")
print(df.shape)

print("\n=== Column Names ===")
print(df.columns.tolist())

"""**Step 4** gives you a quick structural snapshot of the dataset you just loaded by printing its shape and listing all column names. This confirms how many rows and variables you’re working with and ensures the dataset loaded correctly and completely. By surfacing both the dimensionality and the feature list, you establish a clear understanding of the dataset’s scope before moving into deeper cleaning or modeling.

**(Why This Step Matters)**
This step matters because understanding the dataset’s structure is foundational for every downstream decision—cleaning strategies, feature engineering, modeling choices, and computational planning all depend on knowing how many rows you have and what variables exist. In clinical research workflows, where datasets can be large and complex, confirming structure early prevents subtle errors, ensures reproducibility, and helps you catch issues (such as truncated files or missing columns) before they propagate into later steps.
"""

# 5. Assess Missing Data Across All Variables
print("\n=== Missing Values ===")
print(df.isnull().sum())

"""**Step 5** evaluates the completeness of your dataset by calculating the number of missing values in each column using df.isnull().sum(). The output shows a clean dataset with zero missing values across all variables, confirming that no additional imputation or data-recovery steps are required before moving deeper into preprocessing or modeling. This quick diagnostic gives you confidence that the dataset is structurally sound and ready for more advanced analysis.

**(Why This Step Matters)**
Missing data can distort statistical relationships, bias model training, and undermine the validity of clinical research findings. Detecting missingness early ensures that you either address it appropriately or confirm that no corrective action is needed. For large clinical datasets—especially those used for prediction modeling—verifying completeness protects the integrity of the workflow and prevents subtle issues from propagating into feature engineering, model fitting, or evaluation.
"""

# 6. Review Descriptive Statistics for All Features
print("\n=== Summary Statistics ===")
print(df.describe(include='all'))

"""**Step 6** generates a full descriptive overview of every variable in the dataset by calling df.describe(include='all'), which produces counts, unique values, most frequent categories, and basic distribution information for both numeric and categorical features. This gives you an immediate, high‑level understanding of how each variable behaves, what categories dominate, and whether the dataset contains any anomalies or unexpected patterns. Even though many numeric summary fields appear as NaN for categorical variables, the categorical statistics (count, unique, top, freq) provide meaningful insight into the structure of the data.

**(Why This Step Matters)**
Understanding the statistical profile of each variable is essential for designing a reliable clinical prediction pipeline. Summary statistics reveal imbalances (e.g., heavily skewed categories), unexpected values, or variables that may need recoding before modeling. They also help you anticipate modeling challenges—such as high-cardinality features, dominant categories, or variables that lack numeric structure. In clinical datasets, where variable meaning and distribution directly affect interpretability and fairness, this early statistical scan ensures that downstream preprocessing and modeling decisions are grounded in a clear understanding of the data.
"""

# 7. Verify Variable Data Types
print("\n=== Data Types ===")
print(df.dtypes)

"""**Step 7** examines the underlying data types of every column in the DataFrame so you can see which variables are stored as integers, floats, or objects (typically strings or categorical values). The output shows a mix of numeric fields like Patient_ID, Age, and BMI, alongside many object‑typed variables that represent categorical information such as Gender, Race, Stage_at_Diagnosis, and treatment‑related fields. This snapshot clarifies how the dataset is encoded and what transformations may be needed before modeling.

**(Why This Step Matters)**
Data types drive nearly every downstream decision in a clinical prediction pipeline. Models require numeric inputs, so categorical variables must be encoded; summary statistics depend on correct typing; and data‑cleaning steps such as outlier detection or normalization only work on numeric fields. Misclassified types can silently break analyses or distort model behavior. By confirming data types early, you ensure that preprocessing is accurate, reproducible, and aligned with the clinical meaning of each variable.
"""

# 8. Identify and Count Duplicate Records
duplicates = df.duplicated().sum()
print(f"\n=== Duplicate Rows: {duplicates} ===")

"""**Step 8** evaluates whether the dataset contains any duplicated rows by using df.duplicated().sum(), which counts how many records appear more than once. The output shows 0 duplicates, confirming that every row in the dataset is unique. This quick integrity check ensures that no patient records or observations are unintentionally repeated, which is essential for maintaining the validity of downstream statistical analysis and predictive modeling.

**(Why This Step Matters)**
Duplicate records can seriously compromise the integrity of clinical research pipelines. They can artificially strengthen associations, skew prevalence estimates, and cause machine‑learning models to overfit by repeatedly seeing the same data points. Detecting duplicates at this stage ensures that the dataset reflects true, independent observations—critical for reproducibility, fairness, and accurate predictive performance. In large clinical datasets, this check prevents subtle errors from propagating into later stages of analysis.
"""

# 9. Profile Unique Categories in Categorical Variables
categorical_cols = df.select_dtypes(include=['object']).columns
print("\n=== Unique Values (Categorical Columns) ===")
for col in categorical_cols:
    print(f"{col}: {df[col].nunique()} unique values")

"""**Step 9** explores the structure of all categorical variables by identifying how many distinct values each column contains. The code selects every column stored as an object type, loops through them, and prints the number of unique categories for each. This gives you a clear map of the categorical landscape of the dataset—showing which variables are binary, which have moderate diversity, and which may require special handling during preprocessing or modeling.

**(Why This Step Matters)**
Categorical structure directly shapes how you prepare data for machine learning. Variables with only two categories may be encoded simply, while those with several levels may require one‑hot encoding, ordinal encoding, or domain‑specific grouping. In clinical datasets, understanding category diversity is essential for fairness, interpretability, and avoiding sparse or unstable model features. This step ensures you have a clear, quantitative understanding of each categorical variable before moving into encoding or feature engineering.
"""

# 10. Confirm Presence of Target Variable
target_col = "cancer_status"  # adjust if needed
if target_col in df.columns:
    print("\n=== Target Variable Distribution ===")
    print(df[target_col].value_counts())
else:
    print("\n[WARNING] Target variable not found.")

"""**Step 10** checks whether the dataset contains the expected target variable by looking for a column named cancer_status and, if present, printing its class distribution. In this case, the column is missing, so the code prints a warning instead of attempting to analyze the target. This step acts as a safeguard before any modeling work begins, ensuring that the dataset actually includes the outcome you intend to predict.

**Why this step matters**
A prediction pipeline cannot proceed without a clearly defined target variable. If the target is missing, misspelled, or stored under a different name, any modeling code will fail or—worse—train on the wrong variable. Early validation protects the integrity of the workflow, prevents wasted computation, and ensures that the dataset aligns with the intended clinical question. In clinical research, where outcome definitions are critical, this check helps maintain accuracy, reproducibility, and conceptual clarity.
"""