# -*- coding: utf-8 -*-
"""Colon_readme/02_README.md

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gpJoKje-cFWMYk8Sk1PELZSFACVzDFGT

# Colorectal Cancer Prediction — Clinical Dataset Workflow

## Overview
This project analyzes a colorectal cancer clinical dataset. After cleaning and imputing missing values, the dataset is saved as:

`colorectal_cancer_prediction_cleaned_imputed.csv`

The workflow is implemented in Google Colab and includes:
- Mounting Google Drive
- Loading the cleaned dataset
- Exploratory data analysis
- Encoding clinical variables
- Train/test split
- Baseline machine learning model
- Evaluation metrics (AUC, classification report)

## Directory Structure
"""