# -*- coding: utf-8 -*-
"""Prostate_gitignore/04_.gitignore

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jfmuz1-U4k-cXjO2_CpYHN0_mOVDZ5mA

# Python
__pycache__/
*.pyc

# Jupyter
.ipynb_checkpoints/

# Data
data/*.csv
data/*.xlsx
data/*.parquet
*.sav
*.dta

# Models
models/
*.pkl
*.joblib

# Colab / Temp
*.log
*.tmp

# Environment
.env
*.yml

# OS-specific
.DS_Store
Thumbs.db
"""