# -*- coding: utf-8 -*-
"""Colon_license/03_LICENSE

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KfiiBPDANxwPKNPyuCIM1Wsb0aLNrjfc

MIT License

Copyright (c) 2026

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the “Software”), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

[standard MIT text continues…]
"""