# -*- coding: utf-8 -*-
"""Colon_gitignore/04_.gitignore

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FYtaWRBOLHeq8KI9KEAVPeQcv4GWvt1u

# Python
__pycache__/
*.pyc

# Jupyter
.ipynb_checkpoints/

# Data
*.csv
*.xlsx
*.parquet
*.feather
*.sav

# Models
*.pkl
*.joblib

# Environment
.env
*.yml

# OS
.DS_Store
Thumbs.db
"""