# -*- coding: utf-8 -*-
"""Colon_docs/01_project_overview.md

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UtqXbRYXc86ds3H1QGThuyY6es6K4Im7
"""

# Step 1: Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Step 2: Import required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")

# Step 3: Load cleaned colorectal cancer dataset

path = "/content/drive/MyDrive/colorectal_cancer_prediction_cleaned_imputed.csv"
df = pd.read_csv(path)


# Preview first rows
df.head()

# Step 4: Inspect structure and metadata
print("Dataset Shape:", df.shape)
print("\nColumn Types:\n", df.dtypes)

# Summary statistics
df.describe(include='all')

# Step 5: Missingness check
missing_values = df.isnull().sum()
missing_values[missing_values > 0]

import os

# Step 6: Distribution plots for numeric variables
numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns

df[numeric_cols].hist(figsize=(14, 10), bins=20)
plt.tight_layout()
plt.show()

# Create the directory if it doesn't exist
os.makedirs('reports/figures', exist_ok=True)
plt.savefig("reports/figures/Distribution plots.png", dpi=300)
plt.close()

import numpy as np
# Step 7: Correlation heatmap for numeric variables
plt.figure(figsize=(12, 8))
sns.heatmap(df.select_dtypes(include=np.number).corr(), cmap='coolwarm', annot=False)
plt.title("Correlation Heatmap")
plt.show()
plt.savefig("reports/figures/Correlation Heatmap.png", dpi=300)
plt.close()

# Step 8: Count plots for categorical variables
categorical_cols = df.select_dtypes(include=['object']).columns

for col in categorical_cols:
    plt.figure(figsize=(6,4))
    sns.countplot(data=df, x=col)
    plt.title(f"Count Plot: {col}")
    plt.xticks(rotation=45)
    plt.show()
    plt.savefig("reports/figures/Count plots.png", dpi=300)
    plt.close()

# Step 9: Save updated dataset if modifications were made
output_path = "/content/drive/MyDrive/colorectal_cancer_prediction/colorectal_cancer_prediction_updated.csv"
df.to_csv(output_path, index=False)