# -*- coding: utf-8 -*-
"""Colon_environment/01_environment.yml

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NuwXXnb4XLcUWzUJcdpMUdQgTXzRalme

name: colorectal_cancer_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - pip
  - pip:
      - imbalanced-learn
      - pyarrow
"""