# -*- coding: utf-8 -*-
"""Colon_docs/03_references.md

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YP6jyQxBoAHdV98SmfwWvea0DhqudeGg

# References

1. Siegel RL, Miller KD, Jemal A. Cancer statistics, 2024. *CA: A Cancer Journal for Clinicians*.
2. Brenner H, Kloor M, Pox CP. Colorectal cancer. *Lancet*. 2014.
3. Hastie T, Tibshirani R, Friedman J. *The Elements of Statistical Learning*. Springer.
4. Pedregosa F, et al. Scikit-learn: Machine Learning in Python. *Journal of Machine Learning Research*.
5. Kuhn M, Johnson K. *Applied Predictive Modeling*. Springer.
"""