# -*- coding: utf-8 -*-
"""Prostate_readme/02_README.md

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hGKuCM52nsnYaLtTm79IANqCQlpdL8lu

# Prostate Cancer Prediction — Clinical Dataset Pipeline

This project provides a reproducible workflow for analyzing the
**prostate_cancer_prediction_cleaned_imputed.csv** dataset using Google Colab.
The workflow includes environment setup, preprocessing, modeling, evaluation,
and reporting.

## Dataset
- **Source:** prostate_cancer_prediction  
- **Final cleaned file:** `prostate_cancer_prediction_cleaned_imputed.csv`
- **Location:** Google Drive → MyDrive

## Workflow Overview
1. Mount Google Drive in Google Colab  
2. Load cleaned dataset  
3. Perform exploratory data analysis (EDA)  
4. Preprocess clinical variables  
5. Train predictive models  
6. Generate figures, tables, and publication-ready outputs  

## Folder Structure
"""