# -*- coding: utf-8 -*-
"""Colon_tests/02_test_modeling.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JCpOrdvSoAJUqDWbJNgBZgNGsztxMXm3

# ===================================================
# 02_test_modeling.py
# Test script for modeling colorectal cancer dataset
# ===================================================
"""

# 1. Mount Google Drive for Workspace Access
from google.colab import drive
drive.mount('/content/drive')

"""**Step #1** is the environment‑access step where you connect your Google Drive to the Colab runtime so the notebook can read and write files as if they were stored locally. The code imports the Drive module and mounts it at /content/drive, establishing a persistent link between your session and all datasets, scripts, and outputs stored in your Drive. The number section (“1.”) marks this as the first foundational action in the workflow—everything else depends on having reliable access to your project files.

**Why this step matters**
Colab sessions are temporary, so without mounting Drive, any files you load or generate would disappear once the session resets. Mounting Drive ensures reproducibility, lets you maintain a stable project directory, and supports large clinical datasets that cannot be uploaded repeatedly. For research workflows—especially those involving multi‑step preprocessing, modeling, and documentation—this step is essential for keeping your work organized and persistent.
"""

# 2. Import Core Machine Learning Libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

"""**Step #2** is the model‑building setup stage where you load the core libraries needed for splitting data, scaling features, training a logistic regression model, and evaluating its performance. The code imports pandas for DataFrame handling, train_test_split for creating training and testing partitions, StandardScaler for feature normalization, LogisticRegression for building the classifier, and accuracy_score plus classification_report for assessing predictive performance. The number section (“2.”) marks this as the second foundational step—coming right after environment access and establishing the full machine‑learning toolkit your workflow will rely on.

**Why this step matters**
Machine‑learning workflows depend on a consistent set of tools for preparing data, training models, and evaluating results. Importing these libraries early ensures that every downstream step—splitting data, scaling features, fitting models, and generating performance metrics—can run smoothly without interruption. In clinical prediction tasks, this structure is especially important because reproducibility, transparency, and methodological rigor are critical for trustworthy results. This step anchors the workflow in a well‑established, interpretable modeling framework.
"""

# 3. Load the Analytical Dataset
data_path = "/content/drive/MyDrive/colorectal_cancer_prediction_cleaned_imputed.csv"
df = pd.read_csv(data_path)

"""**Step #3** is the data‑loading stage where you bring the cleaned and imputed colorectal cancer dataset into your working environment so it can be explored, transformed, and modeled. The code defines the file path inside your mounted Drive and uses pd.read_csv() to read the dataset into a pandas DataFrame named df, which becomes the central object for all downstream analysis. The number section (“3.”) marks this as the third foundational step—coming right after importing libraries and establishing the environment, and serving as the transition point from setup to working with real data.

**Why this step matters**
Loading the dataset is essential because every analytical and modeling decision depends on having a consistent, reproducible DataFrame available. It ensures that the workflow is tied to a specific, versioned input file, which is critical for transparency in clinical research. It also prevents ambiguity about which dataset was used, supports reproducibility across sessions, and anchors the entire pipeline in a stable data source before any transformations or modeling begin.
"""

print('Available columns:', df.columns.tolist())
# 4. Define Features and Target Variable
target_col = "Survival_Status"  # adjust if needed
X = df.drop(columns=[target_col])
y = df[target_col]

"""**Step #4** is the feature‑definition stage where you formally separate the dataset into predictor variables (X) and the target outcome (y) that the model will learn to predict. The code prints all available columns for transparency, assigns "Survival_Status" as the target column, removes that column from the DataFrame to create the feature matrix X, and stores the target values in y. The number section (“4.”) marks this as the fourth major step in the workflow—coming right after loading the dataset and before any splitting, scaling, or modeling—because defining features and the target is the structural backbone of any supervised learning pipeline.

**Why this step matters**
A supervised model cannot train unless the predictors and target are clearly defined. This step prevents data leakage by ensuring the target column is not accidentally included among the features, which would artificially inflate model performance and invalidate results. In clinical prediction workflows, this separation is especially important because the target often encodes sensitive or outcome‑critical information. Getting this step right ensures the modeling process is transparent, reproducible, and methodologically sound.
"""

# 5. Create Training and Testing Splits
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

"""**Step #5** is the data‑partitioning stage where you split your features and target into training and testing sets so the model can learn patterns on one portion of the data and be evaluated fairly on another. The code uses train_test_split to allocate 80% of the data for training and 20% for testing, fixes a random_state for reproducibility, and applies stratify=y to preserve the class distribution across both sets. The number section (“5.”) marks this as the fifth major step in the workflow—coming right after defining features and the target, and serving as the bridge between data preparation and model training.

**Why this step matters**
A proper train‑test split is essential for evaluating how well a model generalizes beyond the data it was trained on. Without this separation, performance metrics would be inflated and misleading, especially in medical prediction problems where class imbalance and overfitting are common risks. Stratification ensures that both sets reflect the true distribution of the outcome, preventing biased evaluation and supporting more trustworthy model development.
"""

# 6. Encode and Scale Features for Modeling

# Identify categorical columns
categorical_cols = X_train.select_dtypes(include=['object']).columns

# Apply one-hot encoding to categorical columns
X_train_encoded = pd.get_dummies(X_train, columns=categorical_cols, drop_first=True)
X_test_encoded = pd.get_dummies(X_test, columns=categorical_cols, drop_first=True)

# Align columns - this is crucial to ensure both train and test sets have the same columns after one-hot encoding
X_train_encoded, X_test_encoded = X_train_encoded.align(X_test_encoded, join='left', axis=1, fill_value=0)

# Initialize and apply StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_encoded)
X_test_scaled = scaler.transform(X_test_encoded)

# Convert scaled arrays back to DataFrames with column names for better readability (optional)
X_train_scaled = pd.DataFrame(X_train_scaled, columns=X_train_encoded.columns, index=X_train_encoded.index)
X_test_scaled = pd.DataFrame(X_test_scaled, columns=X_test_encoded.columns, index=X_test_encoded.index)

"""**Step #6** is the preprocessing stage where you transform both the training and testing feature sets into a model‑ready format by applying one‑hot encoding to categorical variables, aligning the resulting columns, and scaling all features. The code first identifies categorical columns, expands them into dummy variables, ensures both datasets share the exact same encoded structure, and then standardizes all numeric values using StandardScaler. The number section (“6.”) marks this as the sixth major step in the workflow—coming after splitting the data and before fitting any model—because this is the point where raw features are converted into the numerical, consistent format that machine‑learning algorithms require.

**Why this step matters**
Machine‑learning models cannot interpret raw categorical values, and inconsistent encoding between training and testing sets can cause immediate model failure. One‑hot encoding ensures categorical information is represented numerically, while column alignment prevents mismatches that would otherwise break the pipeline. Scaling is equally important: many models, including logistic regression, are sensitive to differences in feature magnitude. Without scaling, large‑range variables can dominate the model, distort coefficients, and reduce predictive accuracy. This step ensures the model receives clean, consistent, and properly normalized inputs—critical for reliable clinical prediction.
"""

# 7. Train Logistic Regression Model
model = LogisticRegression(max_iter=500)
model.fit(X_train_scaled, y_train)

"""**Step #7** is the model‑training stage where you initialize a logistic regression classifier and fit it to the preprocessed training data so the model can learn the relationship between the predictors and the target outcome. The code creates a LogisticRegression instance with an increased iteration limit (max_iter=500) to ensure convergence, then trains it using the scaled feature matrix and corresponding labels. The number section (“7.”) marks this as the seventh major step in the workflow—coming right after encoding and scaling—because this is the moment where the pipeline shifts from data preparation to actual model learning.

**Why this step matters**
Training the model is the core of any supervised learning workflow. Without fitting the model, there is no learned relationship between features and outcomes, and no basis for prediction. Logistic regression is especially valuable in clinical prediction because it is interpretable, stable, and provides insight into how each feature contributes to the probability of an outcome. Ensuring the model converges properly (via max_iter) is essential for reliable coefficients and trustworthy predictions. This step transforms your cleaned, encoded, and scaled data into a functioning predictive model.
"""

# 8. Generate Test Set Predictions
y_pred = model.predict(X_test_scaled)

"""**Step #8** is the prediction stage where you use the trained logistic regression model to generate outcome predictions for the unseen test data. The code applies model.predict(X_test_scaled) to produce y_pred, a vector of predicted class labels based on the patterns the model learned during training. The number section (“8.”) marks this as the eighth major step in the workflow—coming immediately after model training and serving as the bridge between fitting the model and evaluating how well it performs.

**Why this step matters**
Predictions are essential for determining whether the model generalizes beyond the training data. Without generating y_pred, you cannot compute performance metrics or understand how well the model identifies clinical outcomes. In medical prediction tasks, this step is especially important because it reveals whether the model can reliably classify real‑world cases, detect minority outcomes, and avoid overfitting. It is the first moment where the model’s practical usefulness becomes measurable.
"""

# 9. Evaluate Model Performance
print("\n=== Accuracy ===")
print(accuracy_score(y_test, y_pred))

print("\n=== Classification Report ===")
print(classification_report(y_test, y_pred))

"""**Step #9** is the model‑evaluation stage where you measure how well the trained classifier performed by computing its accuracy and generating a full classification report. The code prints the overall accuracy score and then displays precision, recall, F1‑score, and support for each class, revealing how the model behaves across different outcomes. The number section (“9.”) marks this as the ninth major step in the workflow—coming immediately after generating predictions and serving as the point where model performance becomes transparent and quantifiable.

**Why this step matters**
Evaluation is essential because it tells you whether the model is genuinely learning meaningful patterns or simply defaulting to the majority class. In clinical prediction tasks, this step is especially critical: a model that predicts only “Survived” may achieve high accuracy but completely fail to identify “Deceased” cases, which are often the most clinically important. The classification report exposes these weaknesses by showing precision, recall, and F1‑score for each class, enabling you to diagnose imbalance, adjust preprocessing, or choose a more appropriate model. Without this step, you would have no reliable basis for improving or validating the model.
"""