# -*- coding: utf-8 -*-
"""Prostate_tests/01_test_preprocessing.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PKe8zBD-EiSKuFfYIB4kDe4mFi6BW1ie
"""

# 01_Load Dataset and Initialize Test Environment

import unittest
import pandas as pd
import numpy as np
from google.colab import drive

class TestPreprocessing(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        drive.mount('/content/drive')
        cls.path = "/content/drive/MyDrive/prostate_cancer_prediction/prostate_cancer_prediction_cleaned_imputed.csv"
        cls.df = pd.read_csv(cls.path)

    def test_file_loads(self):
        self.assertIsNotNone(self.df)
        self.assertGreater(len(self.df), 0)

    def test_no_missing_values(self):
        self.assertEqual(self.df.isnull().sum().sum(), 0)

    def test_expected_columns(self):
        expected = [
            "age", "psa_level", "prostate_volume",
            "family_history_Yes", "biopsy_result_Malignant"
        ]
        for col in expected:
            self.assertIn(col, self.df.columns)

    def test_numeric_columns(self):
        numeric_cols = ["age", "psa_level", "prostate_volume"]
        for col in numeric_cols:
            self.assertTrue(np.issubdtype(self.df[col].dtype, np.number))

    def test_value_ranges(self):
        self.assertTrue(self.df["age"].between(30, 100).all())
        self.assertTrue(self.df["psa_level"].between(0, 200).all())

if __name__ == "__main__":
    # This is a common fix for running unittest.main() in IPython/Jupyter environments
    # It prevents unittest from parsing sys.argv and trying to exit the interpreter.
    unittest.main(argv=['first-arg-is-ignored'], exit=False)

"""**Step #1** in your workflow is the part of the script where the testing environment is prepared: Google Drive is mounted, the cleaned/imputed prostate cancer dataset is located, and the DataFrame is loaded into memory. In this step, the setUpClass method runs once before all tests, ensuring that every subsequent unit test operates on the same consistently loaded dataset. It establishes the file path, reads the CSV into cls.df, and confirms that the testing environment has access to the data required for validation.

**(Why This Step Matters)**
This step is foundational because every subsequent test depends on having a correctly loaded, accessible, and stable dataset. If the file path is wrong, the drive isn’t mounted, or the dataset fails to load, all downstream tests would fail or produce misleading results. Ensuring that the dataset is available and valid at the very beginning protects the integrity of the entire preprocessing validation pipeline and prevents silent errors from propagating into later modeling steps.
"""