# -*- coding: utf-8 -*-
"""FSGS_03_test_visualization

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vc5a2yHLA-G9m4PMJEJRWiL53ki_tbix

📁 03_test_visualization.py
"""

#1 Mount Google Drive for File Access

from google.colab import drive
drive.mount('/content/drive')

"""**Step#1:** This initial step sets up access to Google Drive within a Google Colab notebook. By importing the drive module from google.colab and calling drive.mount('/content/drive'), the notebook prompts the user to authorize access to their Google Drive. Once authorized, the Drive is mounted as a virtual file system under /content/drive, allowing seamless reading and writing of files stored in the user's Drive. This is essential for workflows that rely on external datasets, scripts, or outputs saved to Drive."""

#2 Import Core Libraries for Data Analysis"

import pandas as pd
import matplotlib.pyplot as plt

"""**Step#2:** This step prepares the notebook environment for data analysis and visualization by importing two essential Python libraries. pandas is brought in as pd, enabling powerful data manipulation, cleaning, and tabular operations. Simultaneously, matplotlib.pyplot is imported as plt, providing tools for creating a wide range of plots and charts. These imports are foundational for any data science workflow, ensuring that subsequent steps can handle datasets and produce visual insights effectively."""

#3 Test Histogram Generation from Cleaned Data

def test_plot_distribution():
    df = pd.read_csv('/content/drive/MyDrive/fsgs_Kidney_Disease_study/data/processed/fsgs_dataset_cleaned.csv')
    col = df.select_dtypes(include='number').columns[0]
    fig, ax = plt.subplots()
    df[col].hist(ax=ax)
    assert fig is not None, "Histogram failed to generate"

"""**Step#3:** This step defines a test function that verifies whether a histogram plot can be successfully generated from a cleaned dataset. It begins by reading a CSV file containing processed FSGS kidney disease data from Google Drive. The function selects the first numerical column in the dataset, creates a subplot using matplotlib, and plots a histogram of that column. The final line asserts that the figure object is not None, serving as a basic check to confirm that the plot was created without error. This step is useful for validating both data integrity and visualization setup in a reproducible pipeline."""

#4 Test Correlation Plot Generation

def test_plot_correlation():
    df = pd.read_csv('/content/drive/MyDrive/fsgs_Kidney_Disease_study/data/processed/fsgs_dataset_cleaned.csv')
    corr = df.corr()
    fig, ax = plt.subplots()
    cax = ax.matshow(corr)
    assert cax is not None, "Correlation plot failed"

"""**Step#4:** This step defines a test function to verify the successful generation of a correlation plot from the cleaned FSGS kidney disease dataset. It begins by reading the CSV file into a DataFrame, computes the correlation matrix using df.corr(), and then visualizes it with matshow, which displays the matrix as a heatmap. The subplot is created using plt.subplots(), and the final assertion checks that the heatmap object (cax) is not None, confirming that the plot was rendered. This step ensures that the correlation structure of the dataset can be visualized correctly, which is crucial for identifying relationships between numeric features."""