# -*- coding: utf-8 -*-
"""Prostate_tests/02_test_modeling.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11q-hnytPBxtM5irokfEBSu2Slz4fKlEp
"""

# 02_Validate Train–Test Split Integrity

import os
import pandas as pd
import pytest
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

from google.colab import drive
drive.mount('/content/drive')

DATA_PATH = "/content/drive/MyDrive/prostate_cancer_prediction_cleaned_imputed.csv"


def test_train_test_split():
    df = pd.read_csv(DATA_PATH)
    X = df.drop("diagnosis", axis=1)
    y = df["diagnosis"]

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )

    assert len(X_train) > 0
    assert len(X_test) > 0
    assert len(y_train) == len(X_train)
    assert len(y_test) == len(X_test)


def test_model_training():
    df = pd.read_csv(DATA_PATH)
    X = df.drop("diagnosis", axis=1)
    y = df["diagnosis"]

    model = LogisticRegression(max_iter=1000)
    model.fit(X, y)

    assert hasattr(model, "coef_"), "Model coefficients missing after training."
    assert model.coef_.shape[1] == X.shape[1]


def test_prediction_output():
    df = pd.read_csv(DATA_PATH)
    X = df.drop("diagnosis", axis=1)
    y = df["diagnosis"]

    model = LogisticRegression(max_iter=1000)
    model.fit(X, y)

    preds = model.predict(X)
    assert len(preds) == len(X), "Prediction length mismatch."
    assert set(preds).issubset({0, 1}), "Predictions must be binary."

"""**Step #2** in the model‑testing workflow is the part of the script where the integrity of the train–test split is validated. In this step, the dataset is loaded, the target variable is separated from the predictors, and the data is split into training and testing subsets using a fixed random state. The test then checks that each resulting subset is non‑empty and that the lengths of X_train and y_train match, as well as X_test and y_test. This ensures that the split was performed correctly and that the dataset is structured in a way that supports downstream model training and evaluation.

**(Why This Step Matters)**
A faulty train–test split can silently corrupt the entire modeling pipeline. If the target column is missing, mislabeled, or misaligned, the model may train on incorrect data or fail entirely. If the split produces empty or mismatched subsets, downstream tests—such as model training, coefficient validation, or prediction checks—would produce misleading results or crash. Validating the split early protects the integrity of the entire modeling workflow and ensures that subsequent steps evaluate the model rather than structural errors in the data.
"""