# -*- coding: utf-8 -*-
"""Prostate_tests/03_test_visualization.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18yyG__ZMtzyR_f-FjcQHiQxV1uT5B8BM
"""

# 03_Validate Basic Plot Execution

import os
import pandas as pd
import pytest
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

DATA_PATH = "/content/drive/MyDrive/prostate_cancer_prediction_cleaned_imputed.csv"

# Example: import your visualization functions
# from src.visualization import plot_correlation_matrix, plot_feature_importance


def test_dataset_loads():
    df = pd.read_csv(DATA_PATH)
    assert isinstance(df, pd.DataFrame)


def test_matplotlib_import():
    fig = plt.figure()
    assert fig is not None


def test_simple_plot_runs():
    df = pd.read_csv(DATA_PATH)
    plt.figure()
    plt.hist(df["psa"])
    plt.close()
    assert True, "Histogram failed to generate."


# Example test for custom visualization function
# def test_correlation_plot():
#     df = pd.read_csv(DATA_PATH)
#     fig = plot_correlation_matrix(df)
#     assert fig is not None

"""**Step 3** in this visualization‑testing workflow is where you confirm that a basic plot can be generated without errors, using real data from the prostate cancer dataset. In this step, the script loads the dataset, initializes a Matplotlib figure, and produces a simple histogram of the psa variable before closing the figure. The test ends with an assertion that always evaluates to true, meaning the real purpose of the test is to ensure that the plotting commands execute cleanly—no exceptions, no missing columns, no backend issues, and no silent failures in the visualization pipeline.

**(Why This Step Matters)**
Visualization failures often surface only when plots are actually rendered—missing columns, incompatible data types, backend issues, or misconfigured environments can all cause silent or unexpected errors. By confirming that a simple plot runs successfully, this step ensures that the environment is ready for more complex visualizations such as correlation matrices, feature importance charts, or clinical distribution plots. It acts as an early warning system: if this step fails, you know the issue lies in the plotting infrastructure rather than your custom visualization code.
"""