# -*- coding: utf-8 -*-
"""Prostate_environment/01_environment.yml

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lNuMeu57BJS1Qfwk8UYqTeIArCtctYtc

name: prostate_cancer_env
channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.10
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - scipy
  - jupyter
  - pip
  - pip:
      - imbalanced-learn
      - pyjanitor
      - lifelines
"""