# -*- coding: utf-8 -*-
"""Colon_tests/03_test_visualization.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uTa5mYAQRhf4ZRnxG0j1Zeq98Hf-C57o

# ===================================================
03_test_visualization.py
Test script for visualizing colorectal cancer dataset
"""

# 1.Mount Google Drive for File Access
from google.colab import drive
drive.mount('/content/drive')

"""**Step #1** is the initialization step where you mount your Google Drive inside the Colab environment so the notebook can read and write files as if they were part of the local filesystem. The code imports the google.colab.drive module and mounts Drive at /content/drive, which creates a persistent connection between your session and your stored datasets, scripts, and outputs. The number section (“1.”) simply marks this as the first foundational setup task in the workflow, establishing the environment before any data processing or modeling can begin.

**(Why This Step Matters)**
This step matters because Colab sessions are temporary and do not retain files after they end. By mounting Drive, you ensure that your work is reproducible, persistent, and organized across sessions. It also allows you to integrate large datasets or multi-step workflows without losing progress, which is essential for clinical research pipelines, modeling experiments, and publication-ready documentation.
"""

# 2. mport Core Data and Visualization Libraries
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

"""**Step #2** is the environment‑setup stage where you load the core Python libraries that power your data workflow. The code imports pandas for data manipulation, seaborn for statistical visualization, and matplotlib.pyplot for general plotting. The number section (“2.”) marks this as the second foundational action in the workflow—coming immediately after environment access and before any data loading or analysis. This step establishes the analytical toolkit your notebook will rely on for everything from reading datasets to producing publication‑ready figures.

**Why this step matters**
Importing these libraries early ensures that every downstream step—data loading, wrangling, exploratory analysis, feature engineering, and visualization—has the tools it needs already available. It also standardizes your workflow so collaborators know exactly which packages are in use, which is essential for reproducibility, debugging, and maintaining a clean, professional research pipeline. Without this step, nothing else in the notebook could run reliably because the core functions for handling data and generating figures would be missing.
"""

# 3. Load the Analytical Dataset
data_path = "/content/drive/MyDrive/colorectal_cancer_prediction_cleaned_imputed.csv"
df = pd.read_csv(data_path)

"""**Step #3** is the data‑ingestion stage where you bring your cleaned and imputed colorectal cancer dataset into the notebook so it can be explored, transformed, and modeled. The code defines the file’s location in your mounted Drive and uses pd.read_csv() to load it into a pandas DataFrame named df, which becomes the central object the rest of the workflow operates on. The number section (“3.”) marks this as the third foundational action—coming after environment setup and library imports, and serving as the bridge between preparation and actual analytical work.

**Why this step matters**
Loading the dataset is essential because every subsequent step—data inspection, cleaning validation, feature engineering, modeling, and visualization—depends on having a structured DataFrame available. Without this step, the workflow has no data to operate on, and reproducibility would suffer because the analysis would not be tied to a clearly defined, versioned input file. It also ensures that collaborators know exactly which dataset was used, which is critical for clinical research transparency and publication‑ready documentation.
"""

# 4. Visualize Numeric Variable Distributions
numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns

for col in numeric_cols:
    plt.figure(figsize=(6,4))
    sns.histplot(df[col], kde=True)
    plt.title(f"Distribution of {col}")
    plt.show()

"""**Step #4** is the exploratory‑visualization stage where you generate distribution plots for every numeric variable in your dataset to understand how each feature behaves before modeling. The code identifies all numeric columns, loops through them, and produces a histogram with an overlaid KDE curve for each variable, giving you a quick visual sense of skewness, modality, outliers, and general shape. The number section (“4.”) marks this as the fourth major step in the workflow—coming after loading the dataset and serving as the first substantive quality‑check on the data itself.

**Why this step matters**
Distribution plots are essential for detecting issues that can undermine downstream modeling—such as extreme skew, heavy tails, multimodal patterns, or unexpected clustering. They also help you confirm that imputation, cleaning, and preprocessing steps behaved as expected. In clinical prediction workflows, understanding variable distributions is especially important because many algorithms assume certain shapes or are sensitive to outliers. This step ensures you enter feature engineering and modeling with a grounded understanding of the data’s structure.
"""

# 5. Visualize Correlation Structure with a Heatmap
plt.figure(figsize=(12,10))
sns.heatmap(df[numeric_cols].corr(), annot=False, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

"""**Step #5** is the relationship‑mapping stage where you compute and visualize the correlations among all numeric variables in your dataset using a heatmap. The code creates a large figure, calculates the correlation matrix from the numeric columns, and displays it with a diverging “coolwarm” color scale to highlight positive and negative relationships. The number section (“5.”) marks this as the fifth major step in the workflow—coming after distribution checks and serving as your first structured look at how variables interact with one another.

**Why this step matters**
Correlation structure is essential for identifying redundant features, potential multicollinearity, and clinically meaningful relationships that may influence model behavior. Highly correlated predictors can distort coefficient‑based models, inflate variance, or mask important signals. In clinical prediction workflows, understanding these relationships early helps guide feature selection, model choice, and interpretation strategies. This step ensures you enter modeling with a clear sense of which variables move together and which stand alone.
"""

# 6. Assess Target Variable Distribution
target_col = "cancer_status"  # adjust if needed
if target_col in df.columns:
    plt.figure(figsize=(6,4))
    sns.countplot(x=df[target_col])
    plt.title("Target Variable Distribution")
    plt.show()
else:
    print("\n[WARNING] Target variable not found.")

"""**Step #6** is the target‑assessment stage where you verify that the outcome variable exists in the dataset and then visualize its class distribution using a count plot. The code checks whether "cancer_status" is present in the DataFrame, and if so, it generates a bar chart showing how many observations fall into each category of the target. The number section (“6.”) marks this as the sixth major step in the workflow—coming after exploratory checks on numeric features and shifting attention toward understanding the structure of the prediction target itself.

**Why this step matters**
Understanding the distribution of the target variable is essential for designing a reliable predictive model. If the classes are imbalanced, certain algorithms may overfit to the majority class or fail to detect minority‑class patterns—an especially important concern in clinical prediction tasks where positive cases may be rare but clinically significant. This step ensures you recognize imbalance early, allowing you to plan appropriate strategies such as resampling, class weighting, or algorithm selection. It also serves as a sanity check that the dataset contains the correct outcome variable before modeling begins.
"""