# -*- coding: utf-8 -*-
"""Prostate_docs/03_references.md

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tEl7bQwBN_QRSxc3Vu0MTqiGskG9N9r9

# 03_references.md  
## References

1. Harrell FE. *Regression Modeling Strategies*. Springer.  
2. Kuhn M, Johnson K. *Applied Predictive Modeling*. Springer.  
3. Hastie T, Tibshirani R, Friedman J. *The Elements of Statistical Learning*.  
4. TRIPOD Statement: Transparent Reporting of a multivariable prediction model for Individual Prognosis Or Diagnosis.  
5. Standard clinical guidelines for prostate cancer screening and diagnosis (AUA, NCCN).
"""