# -*- coding: utf-8 -*-
"""Colon_docs/02_methods.md

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19r6Yr6qy28ONSF1DJTwoOFzgl68Ow2k1

# Methods

## Study Design
Retrospective analysis of a structured clinical dataset for colorectal cancer prediction.

## Data Processing
- Loaded dataset from Google Drive using Google Colab.
- Cleaned missing values using domain-informed imputation.
- Standardized continuous variables and encoded categorical variables.
- Validated imputation using missingness heatmaps and summary statistics.

## Exploratory Data Analysis
- Distribution plots for demographic and clinical variables.
- Correlation matrix to identify multicollinearity.
- Outlier detection using boxplots and z-score thresholds.

## Modeling Approach
### Baseline Model
- Logistic Regression with L2 regularization.
- Evaluated using accuracy, precision, recall, F1-score, and AUC.

### Additional Models (Optional)
- Random Forest
- Gradient Boosting (XGBoost, LightGBM)
- Support Vector Machines

## Evaluation Strategy
- Train/test split (80/20) with stratification.
- ROC curves and AUC for discrimination.
- Confusion matrix for classification performance.
- Feature importance analysis for interpretability.

## Reproducibility
- All code executed in Google Colab.
- Dataset stored in Google Drive for persistent access.
- Modular code blocks for clarity and reuse.
"""